version: "3.9"
services:
#  test:
#    image: "exercise-1"
#    volumes:
#      - .:/app
#    command: python3 -m pytest
  run:
    build: .
#    image: "exercise-1"
    volumes:
      - ./downloads:/app/downloads
      - dupa-volume:/logs
    command: python3 main.py
volumes:
  dupa-volume: